better-rail/app

app/components/route-details-header/route-details-header.tsx
On LTR mode, the route details header displays the stations swapped (origin station becomes the destination and vice versa)
<div style="display:flex;">
</div>
This PR fixes the issue by removing the layout reversing on LTR mode.
=> Fixed incorrect route details header on LTR mode

app/i18n/formatted-date.ts
Closes #84 
It happened becouse the `now` variable was stuck on the previous day if the app was at the background for a long time. So now we'll recreate it every time we need to calculate the formatted date.
=> Fixed tomorrow day bug

ios/BetterRailWidget/Views/WidgetEntryView.swift
Use `NSLocalizedString` to provide the localized string.
=> Fixed `No trains found` message localization on widget

app/hooks/use-deep-linking.ts, app/screens/route-details/route-details-screen.tsx, app/utils/helpers/ride-helpers.ts, ios/BetterRailWidget/Live Activity/BetterRailLiveActivity.swift, package.json, yarn.lock
also
- fixed a line state on routes with no exchange
- switched to use lodash `isEqual` method when checking for array equality in one of the ride helper methods.
=> Deep link to active ride screen if app is on `routeDetails` but not on the activity's route

app/hooks/use-ride-progress/use-ride-route.ts, app/models/ride/ride.ts, app/screens/route-details/components/index.ts, app/screens/route-details/components/live-ride-sheet.tsx, app/screens/route-details/route-details-screen.tsx, app/utils/helpers/ride-helpers.ts
The ride progress hooks are using the `RouteItem` from the navigation params. 
When the route is being updated, we try to update the navigation params through `navigation.setParams`, but it seems like the method not stable - so it's better not rely on it and use the route from the `ride` store instead.
Also, the delay value that was being used to calculate the `nextStationId` was missing the conversion to milliseconds, hence the clunky details progress view.
=> Fix `route` navigation param not updating & incorrect delay calculation

app/components/station-card/station-card.tsx, app/screens/select-station/recent-searches-box/recent-searches-box.tsx, app/screens/select-station/recent-searches-box/station-search-entry.tsx
```
View #5993 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.
```
=> Fixed view shadow calculation warnings

ios/BetterRailWidget/BetterRailWidget.swift, ios/BetterRailWidget/EntriesGenerator.swift, ios/BetterRailWidget/Views/WidgetEntryView.swift, ios/BetterRailWidget/Views/WidgetLargeScheduleView.swift, ios/WatchBetterRail Extension/Models/RouteModel.swift, ios/WatchBetterRail Extension/ViewModels/RouteViewModel.swift, ios/ar.lproj/Localizable.strings, ios/en.lproj/Localizable.strings, ios/he.lproj/Localizable.strings, ios/ru.lproj/Localizable.strings
changed the API method to return the status of the request (`success` or `failed`).
In case request has been failed, the widget timeline will try to refetch every 30 minutes.
=> Fixed widget referesh timeline

ios/BetterRailWidget/Live Activity/Views/Lock Screen/InTransitView.swift, ios/BetterRailWidget/Live Activity/Views/Lock Screen/WaitForTrainView.swift, ios/BetterRailWidget/Live Activity/Views/TimeInformation.swift
using `isRTL` instead of `isEnglish` since somehow the live activities UI thinks the device is in English, even though the device main locale is English (condition is OK inside the app)
Resolves #185
=> Improve Live Activities UI on Hebrew

app/i18n/i18n.ts
if the device language isn't Hebrew, Arabic or Russian the app will set the user language to English 
Fixed #201
=> Resolved issue with black screen when device language is not supported

ios/BetterRailWidget/EntriesGenerator.swift, ios/Utilities.swift, ios/WatchBetterRail Extension/Models/RouteModel.swift
Closes #205
- Added `he_IL` locale and `setLocalizedDateFormatFromTemplate` to all date formatters fix duplicate times issue.
- Widget currently shows trains for Sunday when it's Friday and there are no trains in Friday **and** Saturday, so there's a fix for that as well.
=> Fixed widget duplicate times

ios/BetterRailWidget/Live Activity/BetterRailLiveActivity.swift, ios/BetterRailWidget/Live Activity/Views/CircularProgressView.swift
Instead of showing the logo, show the minutes to the ride completion:
=> Show Minutes Left In Dynamic Island Minimal View

app/screens/route-details/route-details-screen.tsx
Related only to iOS users, so it's unnecessary to render it on Android devices.
=> Avoid rendering first ride alert sheet on Android

app/screens/settings/settings-about-screen.tsx
> encodeURI is used to encode a full URL whereas encodeURIComponent is used for encoding a URI component such as a query string.
[Source](https://stackoverflow.com/a/67782707/3232187)
=> Fix feedback link not working on iOS

app/components/sheets/bottom-screen-sheet.tsx, app/screens/route-details/route-details-screen.tsx
=> fix first ride alert sheet overflows bottom ride details

app/screens/planner/planner-screen-header.tsx
Also don't display the "new" badge in case urgent bar is displayed. 
Resolves #339
=> Hide urgent bar during active rides

android/app/build.gradle, app/app.tsx, app/screens/settings/settings-tip-jar-screen.tsx, ios/BetterRail.xcodeproj/project.pbxproj, ios/BetterRail/Info.plist, ios/BetterRailWidget/Info.plist, ios/StationIntent/Info.plist, ios/WatchBetterRail Extension/Info.plist, ios/WatchBetterRail/Info.plist
Tipping on Android were always refunded after a few days. 
The reason is that we didn't flush the purchase ("acknowledge" it to the play store):
> your app must then acknowledge the purchase. This acknowledgement communicates to Google Play that you have granted entitlement for the purchase.
We had the flushing mechanism set in the `TipJarScreen`, but putting it there will possibly hav the flushing effect not run (if the user has exit the screen before it ran, or for whatever reason else. Putting in the main `App` component will ensure it'll be flushed, either in the current session or in the next app relaunch.
=> Fix android tip jar refunds

app/models/favorites/favorites.ts
Due to this warning log:
```
10.7.0 - [FirebaseAnalytics][I-ACS013000] User property name is too long. The maximum supported length is 24: apple_watch_app_installed
```
=> Shorten Apple Watch analytics event names

app/screens/route-details/components/start-ride-button.tsx
=> Consider route delay for accurate start ride button disabled state

app/app.tsx, app/models/ride/ride.ts, app/screens/planner/planner-screen-header.tsx, app/screens/route-details/components/start-ride-button.tsx, app/screens/route-details/route-details-screen.tsx, app/utils/ios-helpers.tsx, ios/BetterRail.xcodeproj/project.pbxproj, ios/BetterRail/Info.plist, ios/BetterRail/RNBetterRail.swift, ios/BetterRailWidget/Info.plist, ios/BetterRailWidget/WatchInfo.plist, ios/RNBetterRail.m, ios/StationIntent/Info.plist
The crash occurred because the live activities monitoring method initialized on the Mac app, where it's not available
Resolves #346
=> Fix crash when launching the app on MacOS

app/screens/select-station/recent-searches-box/recent-searches-box.tsx
A small improvement for the recent searches box - now it snaps to the nearest item during scroll, instead of being (possibly) _[stuck in the middle](https://www.youtube.com/watch?v=ln7Vn_WKkWU)_.
https://github.com/better-rail/app/assets/13344923/f0991703-2d10-44e7-83db-2f70fc94524c
=> Added snap interval to recent searches box

app/components/announcements/announcement-card.tsx, app/components/announcements/urgent-announcements.tsx, app/models/settings/settings.ts, app/screens/planner/planner-screen-header.tsx
- Added `seenUrgentMessagesIds` to the settings store
- Updated the `UrgentAnnouncements` component to support this property
- Added `uniqBy` to uregnt messages avoid duplicate messages provided by the API
The behaviour is after the user closes the urgent modal, the red bar will still be shown. It will be hidden upon re-opening the app.
=> Remove urgent messages upon viewing

android/app/build.gradle, android/app/src/main/java/com/betterrail/MainActivity.kt, ios/BetterRail.xcodeproj/project.pbxproj, ios/Podfile.lock
Crashlytics started to report the following crash on Android devices:
```
Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
```
A thrown error has suggested this fix:
```
Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
```
We had the `MainActivity.java` configured properly, but when migrating to Kotlin on the latest version (2.3.3), we forgot to add it to `MainActivity.kt`.
=> Fix Android crash: Unable to instantiate fragment

app/components/chip/chip.tsx, app/screens/route-list/components/station-hours-sheet.tsx
Beforehand the hours details were aligned to the left on RTL languages.
=> Fix hours sheet RTL alignment

app/theme/color.ts, app/theme/palette.ts, ios/BetterRail.xcodeproj/project.pbxproj
For some reason the `PlatformColor` usage doesn't work specifically on the `inputBackground` color value.  
I couldn't figure out why it behaves like that, but managed to fix it quickly for changing to use hex code color values.
https://github.com/user-attachments/assets/c28a9607-acbc-4015-8f45-719602333d04
Fixes #418.
=> Fix dynamic color not working on `inputBackground`

app/components/route-details-header/route-details-header.tsx
Previously, when adding a exchange-included ride to the calendar, we've used the first train destination. This change ensures we'll use the actual route destination, despite exchanges.
=> Use correct destination when adding an exchange ride to calendar

app/components/station-card/station-card.tsx
This was caused by inconsistent border radius between the background image and the `GARDIENT` style
=> Fix Android border radius showing tiny whitespace

app/navigators/navigation-utilities.tsx, app/screens/route-list/components/station-hours-sheet.tsx
React Native v0.77 removes `BackHandler.removeEventListener` in exchange of `subscription.remove()` (https://github.com/facebook/react-native/pull/45892).
This prepares the app for the upcoming upgrade from v0.76. 
Also in this PR an upgrade for action sheet, which uses that method (https://github.com/expo/react-native-action-sheet/pull/339)
=> Change `BackHandler.removeEventListener` usage to `subscription.remove`

ios/.xcode.env
I had issues with building the project with xcode when I had NVM installed on my machine - got `Command PhaseScriptExecution failed with nonzero exit code` error.
These changes should improve `node` detection by xcode.
=> Improve Node.js detection in Xcode

android/app/src/main/java/com/betterrail/widget/ModernBaseWidgetProvider.kt
```
Fatal Exception: java.lang.IllegalStateException: Application context not initialized
at com.betterrail.widget.ModernBaseWidgetProvider.preferencesRepository_delegate$lambda$1(ModernBaseWidgetProvider.kt:54)
at com.betterrail.widget.ModernBaseWidgetProvider.$r8$lambda$uUp3ArwhdOBKM5je1hp8plYLO-k()
at com.betterrail.widget.ModernBaseWidgetProvider$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83)
at com.betterrail.widget.ModernBaseWidgetProvider.getPreferencesRepository(ModernBaseWidgetProvider.kt:53)
at com.betterrail.widget.ModernBaseWidgetProvider.access$getPreferencesRepository(ModernBaseWidgetProvider.kt:32)
at com.betterrail.widget.ModernBaseWidgetProvider$updateWidget$1.invokeSuspend(ModernBaseWidgetProvider.kt:230)
at …
```
=> Fix: Application context not initialized crash

android/app/build.gradle, bun.lock, ios/BetterRail.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json
Update to notifee/react-native@9.1.8 which includes fix https://github.com/invertase/notifee/pull/1168
```
Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method 
com.facebook.react.jstasks.HeadlessJsTaskContext$Companion.getInstance, parameter context
at com.facebook.react.jstasks.HeadlessJsTaskContext$Companion.getInstance(:2)
at com.facebook.react.jstasks.HeadlessJsTaskContext.getInstance(:2)
at io.invertase.notifee.NotifeeReactUtils.lambda$startHeadlessTask$1(NotifeeReactUtils.java:183)
at io.invertase.notifee.NotifeeReactUtils$ExternalSyntheticLambda1.call(D8$SyntheticClass)
at io.invertase.notifee.NotifeeReactUtils$2$ExternalSyntheticLambda0.run(D8$SyntheticClass)
at android.os.Handler.handleCallback(Handler.java:959)
at …
```
=> Fix: Parameter specified as non-null is null

app/screens/notifications/notifications-select-stations-screen.tsx
I've missed this screen on my previous edge-to-edge iteration, however, looks like it was broken both for android 14 and 15+ 
**Before** (Android 14 | Android 16)
**After** (Android 14 | Android 16)
=> Notifications select stations screen to follow edge-to-edge pattern
