better-rail/app

app/components/favorite-routes/favorite-route-box.tsx
app/components/route-details-header/route-details-header.tsx
app/i18n/ar.json
app/i18n/en.json
app/i18n/he.json
app/models/favorites/favorites.ts
ios/Podfile.lock
package.json
yarn.lock

Changed the menu from action sheet to context menu
@itayganor fyi this is how the menu gonna look on iOS. I've also changed the implementation of `useOnLongPress` a bit to accommodate this change

💄 - Changed favorite route action sheet menu to context menu on iOS

---

app/i18n/i18n.ts
app/screens/settings/settings-about-screen.tsx

Added device info to feedback email

---

app/data/stations.ts
app/i18n/i18n.ts
app/i18n/ru.json
app/screens/settings/settings-language-screen.tsx

Russian translation

---

app/components/favorite-routes/favorite-route-box.tsx

Add option to delete favorite route on Android

---

android/app/build.gradle
android/app/src/main/java/com/betterrail/MainActivity.java

Fix android crash on app launch

---

app/models/train-routes/train-routes.ts
app/screens/route-list/route-list-screen.tsx
app/services/api/api.types.ts
app/services/api/route-api.ts

Hello! 👋
I added back train delays data, I tested it locally and it works great!

Added back train delays

---

app/services/api/route-api.ts
ios/Utilities.swift

on certain scenerios the API return dates for the next day - we need to filter those

Filter API routes to display only today's routes

---

app/data/stations.ts
app/screens/select-station/select-station-screen.tsx

Added search alias to Ben Gurion Airport

---

app/screens/route-list/route-list-screen.tsx
app/services/api/route-api.ts

If I remember correctly how it worked previously, it should work now again

Added back long route warning

---

ios/Podfile.lock
package.json
yarn.lock

upgrade react native to 0.71.7

---

ios/WatchBetterRail Extension/ViewModels/RouteViewModel.swift
ios/WatchBetterRail Extension/Views/RoutesView.swift

Added scroll to relevant ride in route list in Apple Watch

---

ios/Utilities.swift

Force 24h mode in widget

---

app/hooks/use-ride-progress/use-ride-route.ts
app/utils/helpers/ride-helpers.ts

update the navigation `routeItem` & delay in the `updateRide` method instead of `refetchRoute` - a more appropriate place for these updates to occur

Restructure delay updates

---

app/hooks/use-ride-progress/use-ride-route.ts

resolved by updating the `route` value in the ride store

Fix delay not being updated correctly in live view

---

app/screens/planner/planner-screen.tsx

Fixed live button train icon dimensions

---

ios/WatchBetterRail Extension/Views/RoutesView.swift
ios/WatchBetterRail Extension/Views/TrainDetailsViews/StationListItem.swift
ios/en.lproj/Localizable.strings

had to [cast API values from Int to String to make the localization parser work](https://github.com/better-rail/app/commit/381893cf9de4100372d9a38655dc59698ec06827)

Apple Watch localization fixes

---

app/hooks/index.ts
app/hooks/use-is-beta-tester.ts
app/screens/settings/settings-privacy-screen.tsx
app/screens/settings/settings-screen.tsx

also display build number in settings screen for beta testers

Added `isBetaTester` hook

---

.gitignore
android/app/build.gradle
android/build.gradle
app/app.tsx
app/screens/settings/settings-privacy-screen.tsx
firebase.json
ios/BetterRail.xcodeproj/project.pbxproj
ios/Podfile
ios/Podfile.lock
ios/fastlane/Fastfile
package.json
yarn.lock

Added Crashlytics

---

ios/BetterRailWidget/Live Activity/BetterRailLiveActivity.swift
ios/BetterRailWidget/Live Activity/Views/CircularProgressView.swift
ios/BetterRailWidget/Live Activity/Views/RideInformationBar.swift
ios/BetterRailWidget/Live Activity/Views/TimeInformation.swift

Live Activities dynamic island UI fixes

---

app/app.tsx
app/i18n/ar.json
app/i18n/en.json
app/i18n/he.json
app/i18n/ru.json
app/models/ride/ride.ts
app/screens/route-details/components/start-ride-button.tsx
app/utils/ios-helpers.tsx
ios/BetterRail/RNBetterRail.swift
ios/RNBetterRail.m

Show an alert if Live Activities are disabled

---

app/components/route-card/route-card.tsx
app/screens/route-list/route-list-screen.tsx

Fixed Dashed Line

---

ios/BetterRailWidget/Live Activity/Views/TimeInformation.swift
ios/en.lproj/Localizable.strings
ios/he.lproj/Localizable.strings

Revert original time display in Dynamic Island

---

app/app.tsx
app/components/sheets/bottom-alert-sheet.tsx
app/components/sheets/bottom-sheet-modal.tsx
app/i18n/ar.json
app/i18n/en.json
app/i18n/he.json
app/i18n/ru.json
app/screens/route-details/components/first-ride-alert.tsx
app/screens/route-details/components/start-ride-button.tsx
app/screens/route-details/route-details-screen.tsx
ios/Podfile.lock
package.json
yarn.lock

First Ride alert

---

app/app.tsx
app/screens/planner/planner-screen-header.tsx
app/screens/route-details/components/first-ride-alert.tsx
app/screens/route-details/components/start-ride-button.tsx
ios/BetterRail.xcodeproj/project.pbxproj
ios/BetterRail/Info.plist
ios/BetterRailWidget/Info.plist
ios/StationIntent/Info.plist
ios/WatchBetterRail Extension/Info.plist
ios/WatchBetterRail/Info.plist
package.json
yarn.lock

use Sunday, June 11th at 17:00 for starting to display the first ride alert
also fixed the text color on dark mode, and added an observer wrapper to the planner screen header (the component wasn't getting updates from the ride store)

Use static date for displaying first ride alert

---

README.md
android/app/google-services.development.json
ios/BetterRail.xcodeproj/project.pbxproj
ios/BetterRail/Info.plist
ios/BetterRailWidget/Info.plist
ios/GoogleService-Info.development.plist
ios/StationIntent/Info.plist
ios/WatchBetterRail Extension/Info.plist
ios/WatchBetterRail/Info.plist
package.json

onboard new contributors faster by including a development firebase config, which they'll have to rename during the project installation. 
closes #252

Added firebase development config

---

ios/BetterRail.xcodeproj/project.pbxproj
ios/BetterRail/Info.plist
ios/BetterRailWidget/Info.plist
ios/BetterRailWidget/Live Activity/Views/RideInformationBar.swift
ios/StationIntent/Info.plist
ios/WatchBetterRail Extension/Info.plist
ios/WatchBetterRail/Info.plist

Live Activity information bar dynamic island redesign

---

ios/BetterRailWidget/Live Activity/BetterRailLiveActivity.swift

Change dynamic island tint color during delays to purple

---

app/screens/settings/settings-about-screen.tsx
ios/BetterRail.xcodeproj/project.pbxproj
ios/BetterRail/Info.plist
ios/BetterRailWidget/Info.plist
ios/StationIntent/Info.plist
ios/WatchBetterRail Extension/Info.plist
ios/WatchBetterRail/Info.plist

Encode send feedback link

---

app/i18n/ar.json
app/i18n/en.json
app/i18n/he.json
app/i18n/ru.json
app/models/train-routes/train-routes.ts
app/screens/route-list/components/route-list-warning.tsx
app/screens/route-list/route-list-screen.tsx

When there're trains for the selected date but not for the selected hour show an alert:
<p align="center">
</p>

Alert when no trains are found for the selected hour

---

app/services/api/route-api.ts

Minimize the time diff required for the short route badge if other routes are with changes

---

app/screens/route-details/components/start-ride-button.tsx

Fix start ride button on iOS with Hebrew locale

---

app/screens/route-list/route-list-screen.tsx

**Before / After**
<div style="display: flex; max-width: 500px">
</div>
Closes #286

Add bottom offset to search results when warning is displayed

---

app/hooks/use-deep-linking.ts

Update route plan with widget deep link stations

---

app/screens/planner/planner-screen-header.tsx
yarn.lock

Added analytics events on settings & announcements icons presses

Analytics events for header icons

---

app/models/ride/ride.ts
app/screens/route-details/components/start-ride-button.tsx
ios/BetterRail.xcodeproj/project.pbxproj
ios/BetterRail/Info.plist
ios/BetterRailWidget/Info.plist
ios/Podfile.lock
ios/StationIntent/Info.plist
ios/WatchBetterRail Extension/Info.plist
ios/WatchBetterRail/Info.plist
package.json
yarn.lock

Display In App Review prompt on live ride start

---

android/app/build.gradle
app/components/route-card/delay-badge.tsx
app/components/route-card/index.ts
app/components/route-card/route-card.tsx
app/components/route-card/route-indicators.tsx
ios/BetterRail.xcodeproj/project.pbxproj
ios/BetterRail/Info.plist
ios/BetterRailWidget/Info.plist
ios/StationIntent/Info.plist
ios/WatchBetterRail Extension/Info.plist
ios/WatchBetterRail/Info.plist

Display delay indicator alongside short route badge

---

android/app/src/main/res/values-night/colors.xml
android/app/src/main/res/values/colors.xml
app/components/route-card/delay-badge.tsx
app/components/route-card/route-card.tsx
app/components/route-card/route-indicators.tsx
app/theme/color.ts

Contrast "Short Route" badge background on active ride route

---

app/models/ride/ride.ts
app/screens/route-details/components/live-ride-sheet.tsx

Reduce live ride sheet font scaling on Android

---

android/app/build.gradle
app/screens/announcements/use-service-updates.ts
ios/BetterRail.xcodeproj/project.pbxproj
ios/BetterRail/Info.plist
ios/BetterRailWidget/Info.plist
ios/BetterRailWidget/WatchInfo.plist
ios/StationIntent/Info.plist

Favorite stations related service updates are not included in the announcement screen; this PR fixes that.

Include updates from favorite stations in announcements screen

---

app/screens/planner/planner-screen.tsx

As `tx="plan.origin"` is being used

Remove `text` prop from origin `Text` component

---

.dockerignore
Dockerfile
android/gradle.properties
package.json

**Changes Made:**
* Added Cross-Platform Support for Yarn Installation:
* Fixed #373 
* Introduced conditional logic in the Dockerfile to accommodate differences between macOS/Linux and Windows environments during yarn installation.
* Adjusted Firebase configuration steps to ensure compatibility across different operating systems (macOS/Linux vs. Windows).
I've thoroughly tested the changes on both Windows and Linux environments, and they work seamlessly.

Enhanced Cross-Platform Compatibility and Docker Environment Setup

---

android/app/build.gradle
app/utils/notification-helpers.ts
ios/Podfile.lock
package.json
yarn.lock

In order to resolve Play Store rejection regarding `USE_FULL_SCREEN_INTENT` permission.

Updated notifee package to 9.1.2

---

app/i18n/ar.json
app/i18n/en.json
app/i18n/he.json
app/i18n/ru.json
app/models/root-store/root-store.ts
app/screens/settings/settings-privacy-screen.tsx
app/screens/settings/settings-screen.tsx

https://github.com/better-rail/app/issues/402
Please review. Thanks.

allow local app data deletion

---

app/screens/planner/planner-screen-header.tsx

for some reason it was commented out, probably during dev work

Update conditional rendering for new badge display

---

app/screens/notifications/notifications-setup-screen.tsx

Hide setup notification description when no permission granted

---

app/screens/route-list/components/station-hours-sheet.tsx

- Added station name to sheet modal
- Update sheet background on Dark Mode
- Fixed gate scroll view not working on Android
- Prevent default back button behavior on Android

Add station name to station hours sheet

---

app/screens/route-details/route-details-screen.tsx
app/screens/route-list/route-list-screen.tsx
ios/BetterRail.xcodeproj/project.pbxproj

- Fixed loading indicator on origin/destination change in routes list
- Fixed tomorrow's train routes not showing up when no trains today
- Fixed padding at the bottom of the route details list

Final 2.4.0 Bug Fixes

---

android/app/build.gradle
app/screens/route-list/components/station-hours-sheet.tsx

otherwise it impacted the navigation across the whole navigator on Android

Station hours modal: enable back button handler only when modal is open

---

ios/BetterRail.xcodeproj/project.pbxproj
ios/BetterRail/RNBetterRail.swift
ios/BetterRailWidget/Extensions.swift
ios/BetterRailWidget/Live Activity/Activity.swift
ios/BetterRailWidget/Live Activity/ActivityNotificationsAPI.swift
ios/BetterRailWidget/Live Activity/ActivityUtils.swift
ios/Podfile.lock

See https://github.com/better-rail/app/issues/432

Set minimum iOS version to 17

---

app/screens/planner/planner-screen.tsx
app/screens/planner/planner-slider-wrapper.tsx
app/services/firebase/analytics.ts

https://github.com/user-attachments/assets/33345724-5a0b-4924-841e-4b8c1e04ae28

Switch stations using fling gesture

---

app/screens/route-details/components/train-pull-refresh.tsx

Fixes https://github.com/better-rail/app/issues/430

Fix refresh control wrapper overflows route

---

app/screens/select-station/select-station-screen.tsx

FIXED:
Android 14 __________________________________________________________ Android 15+
ORIG:
Android 14 __________________________________________________________ Android 15+

Fix RTL button layout on select station screen

---

app/components/favorite-routes/favorite-route-box.tsx
app/screens/route-list/route-list-screen.tsx
app/utils/helpers/action-sheet-helpers.ts

Action sheet to support dark colorScheme

---

README.md

Fix README.md on Mobile
